name: Atualizar Docs e Deps

# 🚧 DESABILITADO: as linhas abaixo comentadas impedem execução automática
# on:
#   push:
#     branches: [ main ]
#   pull_request:

jobs:
  disabled:
    if: false
    runs-on: ubuntu-latest
    steps:
      - name: Workflow desativado
        run: echo "Este workflow está desativado."